# Generated by Django 4.1.5 on 2023-01-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_receipt_voucher_payment_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='party_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.CharField(max_length=255, null=True)),
                ('dis_doc', models.CharField(max_length=255, null=True)),
                ('dis_thr', models.CharField(max_length=255, null=True)),
                ('desti', models.CharField(max_length=255, null=True)),
                ('agent', models.CharField(max_length=255, null=True)),
                ('bill_no', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(max_length=255, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
