# Generated by Django 4.1.5 on 2023-01-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_party_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_details',
            name='invoice_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
