# Generated by Django 4.1.5 on 2023-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_new_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_buyer',
            name='addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_buyer',
            name='bill_to',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_buyer',
            name='contr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_buyer',
            name='mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_buyer',
            name='stat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
