# Generated by Django 4.1.5 on 2023-02-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_bill_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_details',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
